---
fullname: Stable sort algorithms in Coq
shortname: stablesort
organization: pi8027
action: true
dune: false

synopsis: >-
  Stable sort algorithms and their stability proofs in Coq

description: |-
  This library provides two kinds of optimized mergesort functions written in
  Coq.
  The first kind is non-tail-recursive mergesort functions. In the call-by-need
  evaluation, they allow us to compute the first k smallest elements of a list
  of length n in the optimal O(n + k log k) time complexity of the partial and
  incremental sorting problems. However, the non-tail-recursive merge function
  linearly consumes the call stack and triggers a stack overflow in the
  call-by-value evaluation.
  The second kind is tail-recursive mergesort functions and thus solves the
  above issue in the call-by-value evaluation. However, it does not allow us to
  compute the output incrementally in the optimal O(n + k log k) time regardless
  of the evaluation strategy.
  The point is that the best mergesort function for lists depends on the
  situation, in particular, the evaluation strategy and whether it should be
  incremental or not.

  This library also provides a generic way to prove the correctness (including
  stability) of these mergesort functions. The correctness lemmas in this
  library are overloaded using a canonical structure (`StableSort.function`).
  This structure characterizes stable sort functions, say `sort`, by an abstract
  version of the sort function `asort` parameterized over the type of sorted
  lists and its operators such as merge, the parametricity of `asort`, two
  equational properties that `asort` instantiated with merge and concatenation
  are `sort` and the identity function, respectively. Thus, one may prove the
  stability of a new sorting function by defining its abstract version, using
  the parametricity translation (Paramcoq), and manually providing the
  equational properties.

authors:
- name: Kazuhiko Sakaguchi
  initial: true

opam-file-maintainer: kazuhiko.sakaguchi@inria.fr

license:
  fullname: CeCILL-B Free Software License Agreement
  identifier: CECILL-B
  file: CeCILL-B

supported_coq_versions:
  text: 8.13 or later
  opam: '{>= "8.13"}'

tested_coq_nix_versions:

tested_coq_opam_versions:
- version: '1.13.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.13.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.14.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.15.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.15.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.15.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.15.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.13'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.14'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.17'
  repo: 'mathcomp/mathcomp'
- version: '1.16.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: '1.17.0-coq-8.15'
  repo: 'mathcomp/mathcomp'
- version: '1.17.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.17.0-coq-8.17'
  repo: 'mathcomp/mathcomp'
- version: '1.17.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: '1.18.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.18.0-coq-8.17'
  repo: 'mathcomp/mathcomp'
- version: '1.18.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: '1.19.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '1.19.0-coq-8.17'
  repo: 'mathcomp/mathcomp'
- version: '1.19.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: '1.19.0-coq-8.19'
  repo: 'mathcomp/mathcomp'
- version: '2.0.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '2.0.0-coq-8.17'
  repo: 'mathcomp/mathcomp'
- version: '2.0.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: '2.1.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '2.1.0-coq-8.17'
  repo: 'mathcomp/mathcomp'
- version: '2.1.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: '2.2.0-coq-8.16'
  repo: 'mathcomp/mathcomp'
- version: '2.2.0-coq-8.17'
  repo: 'mathcomp/mathcomp'
- version: '2.2.0-coq-8.18'
  repo: 'mathcomp/mathcomp'
- version: '2.2.0-coq-dev'
  repo: 'mathcomp/mathcomp'
- version: 'coq-8.17'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-8.18'
  repo: 'mathcomp/mathcomp-dev'
- version: 'coq-dev'
  repo: 'mathcomp/mathcomp-dev'

dependencies:
- opam:
    name: coq-mathcomp-ssreflect
    version: '{>= "1.13.0"}'
  description: |-
    [MathComp](https://math-comp.github.io) 1.13.0 or later
- opam:
    name: coq-paramcoq
    version: '{>= "1.1.3"}'
  description: |-
    [Paramcoq](https://github.com/coq-community/paramcoq) 1.1.3 or later

namespace: stablesort

documentation: |-
  ## Credits
  The mergesort functions and the stability proofs provided in this library are
  mostly based on ones in the `path` library of Mathematical Components.
---
